### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by gamingpandax** [IdkWhosThis/DiscordPinger#3]
### I'm getting this error on executing the start.bat file

Started pinging on: MemeMan#8876!
(node:9320) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
type: Value "text" is not int.
    at C:\discord\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:79:15
    at C:\discord\node_modules\snekfetch\src\index.js:215:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9320) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by IdkWhosThis** [comment]
@gamingpandax can you send me your config.js, please? (remove bot's token from the code when you will be sending it there).

**Comment by IdkWhosThis** [comment]
No activity, closing ticket.
